//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EiffiTools.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EiffiTools.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 about 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependency support 的本地化字符串。
        /// </summary>
        internal static string About_S_1 {
            get {
                return ResourceManager.GetString("About_S_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 illustrate 的本地化字符串。
        /// </summary>
        internal static string About_S_2 {
            get {
                return ResourceManager.GetString("About_S_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 💡If a worker wants to do his job well, he must first sharpen his tools!!! 的本地化字符串。
        /// </summary>
        internal static string About_S_3 {
            get {
                return ResourceManager.GetString("About_S_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you have any questions, you can initiate Issues in the project or leave a message on my blog 的本地化字符串。
        /// </summary>
        internal static string About_S_4 {
            get {
                return ResourceManager.GetString("About_S_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 0.0.0.1 的本地化字符串。
        /// </summary>
        internal static string About_S_5 {
            get {
                return ResourceManager.GetString("About_S_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataHarbor 的本地化字符串。
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Posted by SDUT Maxwell Lei 的本地化字符串。
        /// </summary>
        internal static string About_Title_D {
            get {
                return ResourceManager.GetString("About_Title_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional names and their locations: 的本地化字符串。
        /// </summary>
        internal static string AdditionalNameAndLocation {
            get {
                return ResourceManager.GetString("AdditionalNameAndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 automatic shutdown 的本地化字符串。
        /// </summary>
        internal static string AutoClose {
            get {
                return ResourceManager.GetString("AutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silent message notification automatic closing time 的本地化字符串。
        /// </summary>
        internal static string AutoClose_D {
            get {
                return ResourceManager.GetString("AutoClose_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seraphine&apos;s little nest 的本地化字符串。
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 boot 的本地化字符串。
        /// </summary>
        internal static string Booting {
            get {
                return ResourceManager.GetString("Booting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The software starts automatically after the computer is turned on 的本地化字符串。
        /// </summary>
        internal static string Booting_D {
            get {
                return ResourceManager.GetString("Booting_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        internal static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software starts automatically checking for updates 的本地化字符串。
        /// </summary>
        internal static string CheckUpdate_D {
            get {
                return ResourceManager.GetString("CheckUpdate_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 clear the list 的本地化字符串。
        /// </summary>
        internal static string ClearQueue {
            get {
                return ResourceManager.GetString("ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 closure 的本地化字符串。
        /// </summary>
        internal static string CloseMode {
            get {
                return ResourceManager.GetString("CloseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose how to close the software 的本地化字符串。
        /// </summary>
        internal static string CloseMode_D {
            get {
                return ResourceManager.GetString("CloseMode_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit directly 的本地化字符串。
        /// </summary>
        internal static string CloseMode_S_1 {
            get {
                return ResourceManager.GetString("CloseMode_S_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to tray 的本地化字符串。
        /// </summary>
        internal static string CloseMode_S_2 {
            get {
                return ResourceManager.GetString("CloseMode_S_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List 的本地化字符串。
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        internal static string Converted {
            get {
                return ResourceManager.GetString("Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear the conversion queue after the conversion is completed 的本地化字符串。
        /// </summary>
        internal static string ConvertedFileClearQueue {
            get {
                return ResourceManager.GetString("ConvertedFileClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converted file format: 的本地化字符串。
        /// </summary>
        internal static string ConvertedFileFormat {
            get {
                return ResourceManager.GetString("ConvertedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A message notification will pop up after the conversion is completed 的本地化字符串。
        /// </summary>
        internal static string ConvertedFileNotification {
            get {
                return ResourceManager.GetString("ConvertedFileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After the conversion is completed, open the location 的本地化字符串。
        /// </summary>
        internal static string ConvertedFileOpenFolder {
            get {
                return ResourceManager.GetString("ConvertedFileOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping data rearrangement 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C1 {
            get {
                return ResourceManager.GetString("Dashboard_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrange your elemental distribution measurement mapping data into the desired format 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C1_D {
            get {
                return ResourceManager.GetString("Dashboard_C1_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch rename 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C2 {
            get {
                return ResourceManager.GetString("Dashboard_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch custom format renaming 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C2_D {
            get {
                return ResourceManager.GetString("Dashboard_C2_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table extraction 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C3 {
            get {
                return ResourceManager.GetString("Dashboard_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provides a solution for PDF table data extraction 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C3_D {
            get {
                return ResourceManager.GetString("Dashboard_C3_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper information query 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C4 {
            get {
                return ResourceManager.GetString("Dashboard_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quickly understand the paper&apos;s partitions, impact factors and other information 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C4_D {
            get {
                return ResourceManager.GetString("Dashboard_C4_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper download 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C5 {
            get {
                return ResourceManager.GetString("Dashboard_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bring knowledge to everyone 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C5_D {
            get {
                return ResourceManager.GetString("Dashboard_C5_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper polishing 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C6 {
            get {
                return ResourceManager.GetString("Dashboard_C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polish your paper with ChatGPT 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C6_D {
            get {
                return ResourceManager.GetString("Dashboard_C6_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 reminder 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C7 {
            get {
                return ResourceManager.GetString("Dashboard_C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set up scheduled notification reminders 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C7_D {
            get {
                return ResourceManager.GetString("Dashboard_C7_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAJ format conversion 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C8 {
            get {
                return ResourceManager.GetString("Dashboard_C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fuck CAJ 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C8_D {
            get {
                return ResourceManager.GetString("Dashboard_C8_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data collection management 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C9 {
            get {
                return ResourceManager.GetString("Dashboard_C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Efficient statistics, collection and management of your data 的本地化字符串。
        /// </summary>
        internal static string Dashboard_C9_D {
            get {
                return ResourceManager.GetString("Dashboard_C9_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string Data_Page {
            get {
                return ResourceManager.GetString("Data_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database location 的本地化字符串。
        /// </summary>
        internal static string DataLocation {
            get {
                return ResourceManager.GetString("DataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select where you want the collected data files to be stored 的本地化字符串。
        /// </summary>
        internal static string DataLocation_D {
            get {
                return ResourceManager.GetString("DataLocation_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 default 的本地化字符串。
        /// </summary>
        internal static string DataLocation_S_1 {
            get {
                return ResourceManager.GetString("DataLocation_S_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 customize 的本地化字符串。
        /// </summary>
        internal static string DataLocation_S_2 {
            get {
                return ResourceManager.GetString("DataLocation_S_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data management 的本地化字符串。
        /// </summary>
        internal static string DataManagementMode {
            get {
                return ResourceManager.GetString("DataManagementMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose how you want to organize your collected data files 的本地化字符串。
        /// </summary>
        internal static string DataManagementMode_D {
            get {
                return ResourceManager.GetString("DataManagementMode_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not create database 的本地化字符串。
        /// </summary>
        internal static string DataManagementMode_S_1 {
            get {
                return ResourceManager.GetString("DataManagementMode_S_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 build database 的本地化字符串。
        /// </summary>
        internal static string DataManagementMode_S_2 {
            get {
                return ResourceManager.GetString("DataManagementMode_S_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Name: 的本地化字符串。
        /// </summary>
        internal static string DataPage_Create_S1 {
            get {
                return ResourceManager.GetString("DataPage_Create_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Describe: 的本地化字符串。
        /// </summary>
        internal static string DataPage_Create_S2 {
            get {
                return ResourceManager.GetString("DataPage_Create_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DataPage_Datanum {
            get {
                return ResourceManager.GetString("DataPage_Datanum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DataPage_UpdateTime {
            get {
                return ResourceManager.GetString("DataPage_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage management 的本地化字符串。
        /// </summary>
        internal static string DataSaveStorage {
            get {
                return ResourceManager.GetString("DataSaveStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether only one copy of the data collected is retained 的本地化字符串。
        /// </summary>
        internal static string DataSaveStorage_D {
            get {
                return ResourceManager.GetString("DataSaveStorage_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dataset project 的本地化字符串。
        /// </summary>
        internal static string DataSet_Project {
            get {
                return ResourceManager.GetString("DataSet_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a dataset project 的本地化字符串。
        /// </summary>
        internal static string DataSet_Project_Create {
            get {
                return ResourceManager.GetString("DataSet_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create, display, and manage your dataset projects 的本地化字符串。
        /// </summary>
        internal static string DataSet_Project_D {
            get {
                return ResourceManager.GetString("DataSet_Project_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe: 的本地化字符串。
        /// </summary>
        internal static string Describe {
            get {
                return ResourceManager.GetString("Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DocumentCheck_Page {
            get {
                return ResourceManager.GetString("DocumentCheck_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag and drop files or click to select files 的本地化字符串。
        /// </summary>
        internal static string DragOrClick {
            get {
                return ResourceManager.GetString("DragOrClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 quit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File content arrangement: 的本地化字符串。
        /// </summary>
        internal static string FileArrangement {
            get {
                return ResourceManager.GetString("FileArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the language support of the software (some language changes require restarting the software to obtain support) 的本地化字符串。
        /// </summary>
        internal static string Languages_D {
            get {
                return ResourceManager.GetString("Languages_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English (United States) 的本地化字符串。
        /// </summary>
        internal static string Languages_S_enUS {
            get {
                return ResourceManager.GetString("Languages_S_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string Languages_S_zhCN {
            get {
                return ResourceManager.GetString("Languages_S_zhCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping data arrangement 的本地化字符串。
        /// </summary>
        internal static string MappingData_Page {
            get {
                return ResourceManager.GetString("MappingData_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge into one file (same workbook) 的本地化字符串。
        /// </summary>
        internal static string MergeIntoOneFile1 {
            get {
                return ResourceManager.GetString("MergeIntoOneFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge into one file (different workbooks) 的本地化字符串。
        /// </summary>
        internal static string MergeIntoOneFile2 {
            get {
                return ResourceManager.GetString("MergeIntoOneFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 notify 的本地化字符串。
        /// </summary>
        internal static string MessageMode {
            get {
                return ResourceManager.GetString("MessageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select software message notification method 的本地化字符串。
        /// </summary>
        internal static string MessageMode_D {
            get {
                return ResourceManager.GetString("MessageMode_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 silent notification 的本地化字符串。
        /// </summary>
        internal static string MessageMode_S_1 {
            get {
                return ResourceManager.GetString("MessageMode_S_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pop-up notification 的本地化字符串。
        /// </summary>
        internal static string MessageMode_S_2 {
            get {
                return ResourceManager.GetString("MessageMode_S_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New file storage location: 的本地化字符串。
        /// </summary>
        internal static string NewFileLocation {
            get {
                return ResourceManager.GetString("NewFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New name ➡️: 的本地化字符串。
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open conversion file location 的本地化字符串。
        /// </summary>
        internal static string OpenConvertedFileFolder {
            get {
                return ResourceManager.GetString("OpenConvertedFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the database location 的本地化字符串。
        /// </summary>
        internal static string OpenDatabaseLocation {
            get {
                return ResourceManager.GetString("OpenDatabaseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 prefix 的本地化字符串。
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set up 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 show 的本地化字符串。
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 suffix 的本地化字符串。
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set your theme style 的本地化字符串。
        /// </summary>
        internal static string Theme_D {
            get {
                return ResourceManager.GetString("Theme_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string Theme_S_Dark {
            get {
                return ResourceManager.GetString("Theme_S_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string Theme_S_Light {
            get {
                return ResourceManager.GetString("Theme_S_Light", resourceCulture);
            }
        }
    }
}
